import { ExtensionType } from '@app/types/enum';

const COMMON_CONTENTS = {
  go_to_order_summary: 'Go to order summary',
  go_to_checkout: 'Go to checkout',
  go_to_cart: 'Go to cart',
  sku: 'SKU',
  product: 'Product',
  quantity: 'Quantity',
  total: 'Total',
  minimum: 'Minimum',
  maximum: 'Maximum',
  increment: 'Increment',
  save: 'Save',
  cancel: 'Cancel',
  submit: 'Submit',
  back: 'Back',
  close: 'Close',
  edit: 'Edit',
  action: 'Action',
  view: 'View',
  duplicate: 'Duplicate',
  delete: 'Delete',
  create: 'Create',
  more_actions: 'More actions',
  search: 'Search',
  load_more: 'Load more',
  actions: 'Actions',
  shopping_list_created: 'Shopping list created',
  items: 'Items',
  product_info: 'Product info',
  subtotal: 'Subtotal',
  approve: 'Approve',
  accept: 'Accept',
  reject: 'Reject',
  confirm_reject: 'Confirm reject',
  placeholder_reason: 'E.g. I need better offer...',
  create_order: 'Create order',
  below_min_and_step: 'The quantity must be bigger than {{min}} and increment by {{step}}',
  out_of_range_and_step: 'The quantity must be between {{min}} and {{max}}, and increment by {{step}}',
  exceed_inventory: "The quantity has exceeded the current line item's inventory limit",
  minimum_rule: 'Minimum of {{min}}',
  maximum_rule: 'Maximum of {{max}}',
  increment_rule: 'Increments of {{step}}',
  available_stock: 'Available Stock: {{stock}}',
  status: 'Status',
  phone: 'Phone',
  email: 'Email',
  last_update: 'Last update',
  add: 'Add',
  ea: 'ea',
  test: 'Test',
};

const VARIANT_PICKER_CONTENTS = {
  variant_picker_modal_title: 'Search products or SKUs',
  variant_picker_search_label: 'Enter product name or SKU',
  empty_products: 'Can not find any products with this filter',
};

const CSV_UPLOAD_CONTENTS = {
  ...COMMON_CONTENTS,
  title: 'Bulk order using CSV',
  sub_title: 'Download the product catalog, update quantities, and upload the CSV to place your order. Ensure the shopping location matches the one selected on the shop website before uploading.',
  upload_csv: 'Upload CSV',
  re_upload_csv: 'Re-upload CSV',
  remove_csv: 'Remove CSV',
  upload_csv_modal_title: 'Upload Your Order (CSV)',
  open_catalog: 'Download catalog',
  invalid_format: 'The CSV file has an invalid format.',
  empty_file: 'The CSV file is empty or contains only the header.',
  missing_required_columns: 'Missing required columns: {{missingColumns}}',
  missing_required_values_columns: 'Missing required values in columns: {{missingFields}}',
  invalid_values_columns: 'Invalid numeric values in columns: {{invalidNumberFields}}',
  no_product: 'The selected variant does not exist.',
  not_available: 'This item is not available in your location.',
  duplicate_product: 'This item appears more than once in the cart.',
  below_min_quantity: 'The quantity selected is below the minimum allowed.',
  exceed_max_quantity: 'The quantity selected exceeds the allowed maximum.',
  not_follow_increment: 'The quantity selected does not follow the required increment steps.',
  exceed_inventory: 'The selected quantity exceeds available stock.',
  location_choose: 'Choose your location',
  location_search_placeholder: 'Search location',
  location_select: 'Select location',
  location_change_warning: 'If you change your location, the current catalog may not be available. The CSV file you uploaded will be deleted.',
  order_summary: 'Order Summary',
  show_summary: 'Show Summary',
  hide_summary: 'Hide Summary',
  available_stock: 'Available Stock',
  inventory_not_tracked: 'Inventory not tracked',
  create_another_order: 'Create another order',
  create_shopping_list: 'Create shopping list',
  error_title: 'Error! Please resolve the below issues and re-upload the CSV catalog',
  error_show_more: 'Show more',
  selected_file: 'Selected file',
  download_catalog: 'Load catalog',
};

const QUICK_ORDER_CONTENTS = {
  ...COMMON_CONTENTS,
  ...VARIANT_PICKER_CONTENTS,
  link_title: 'Quick order using SKU',
  link_sub_title: 'Simply enter the desired product or variant SKUs and quantities to be added to the cart',
  page_title: 'Quick order',
  page_sub_title: 'Simply enter the desired product or variant SKUs and quantities to be added to the cart',
  open_catalog: 'Download catalog',
  download_catalog: 'Load catalog',
  go_to_quick_order: 'Go to Quick order',
  no_product: 'There is no products with this SKU',
  empty_field: 'Please fill out this sku input',
  duplicate_product: 'This sku is already exist in this order list',
  not_available: "This sku's product variant is not available in current location",
  location_title: 'Select location you are buying for:',
  location_next_step_button: 'Go to add SKUs',
  location_banner_info: 'Please make sure shopping location matches the one selected on the shop website.',
  location_choose: 'Choose your location',
  location_search_placeholder: 'Search location',
  location_select: 'Select location',
  banner_item_added_description: 'Your selected SKUs has been added to {{pageType}}. Please continue to {{pageType}} page to complete your purchase',
  banner_button: `Go to {{pageType}}`,
  bulk_add_skus: 'Bulk add SKUs',
  ordering_from: 'Ordering from:',
  provide_sku_quantity: 'Provide the SKUs & quantities you wish to order:',
  order_summary: 'Order Summary',
  update_order_summary: 'Update order summary',
  processing_order: 'Processing order...',
  no_item_in_order: 'No items in order',
  click_update_order_summary: 'Click update order summary button to update item in order',
  available_stock: 'Available Stock',
  inventory_not_tracked: 'Inventory not tracked',
  clear_all_line: 'Are you sure you want to clear all lines?',
  clear_all: 'Clear all',
  clear_all_confirmation: 'Clear all confirmation',
  create_another_order: 'Create another order',
  create_shopping_list: 'Create shopping list',
  thank_you: 'Thank you!',
  step_choose_location: 'Choose ordering location',
  step_input_sku: 'Input SKU',
  step_create_order: 'Create order',
  bulk_sku_modal_title: 'Bulk add SKUs',
  bulk_sku_modal_activator: 'Bulk add SKUs',
  bulk_sku_modal_help_text: 'Enter multiple SKUs and quantity separate by new lines. For example:',
  bulk_sku_modal_action: 'Add to order',
  bulk_sku_wrong_format: 'Your input has wrong format.',
  bulk_sku_duplicate: 'You have some duplicated skus: {{skus}}',
  bulk_sku_not_available: 'You have some skus that are not available in current location: {{skus}}.',
  bulk_sku_not_exist: 'You have some invalid skus: {{skus}}.',
  bulk_sku_exceed_limit: 'You can not add more than 100 skus at once',
  add_line: 'Add more line',
  search_sku: 'Search SKU',
  back_to_skus: 'Back to SKUs',
  shipping: 'Shipping',
  estimated_taxes: 'Estimated taxes',
};

const SHOPPING_LIST_CONTENTS = {
  ...COMMON_CONTENTS,
  ...QUICK_ORDER_CONTENTS,
  ...CSV_UPLOAD_CONTENTS,
  ...VARIANT_PICKER_CONTENTS,
  quick_add_skus: 'Quick add SKUs',
  add_line: 'Add more line',
  page_title: 'Shopping Lists',
  status_all: 'All',
  status_pending: 'Pending',
  status_approved: 'Approved',
  status_rejected: 'Rejected',
  status_draft: 'Draft',
  image: 'Image',
  name: 'Name',
  number_of_item: 'Number of items',
  created_by: 'Created by',
  ordering_location: 'Ordering location',
  create_new: 'Create new',
  updated_at: 'Updated at {{time}}',
  note_placeholder: 'Note (optional)',
  go_to_checkout: 'Go to checkout',
  order_from: 'Ordering from',
  add_to_shopping_list: 'Add to shopping list',
  empty_shopping_list_placeholder: 'Add products to your list by searching product name, or uploading a CSV file.',
  search_by_product_name: 'Search by product name',
  error_shopping_list_banner_title: 'Error! Please resolve the below issues and retry',
  error_invalid_quantity: 'Some items have invalid quantity: {{titles}}',
  error_not_in_location: 'Some items are not in current selected location: {{titles}}',
  empty_shopping_list_table_placeholder: 'Let\'s create your first shopping list',
  empty_shopping_list_table_placeholder_header: 'No shopping list yet',
  create_shopping_list: 'Create new shopping list',
  delete_modal_title: 'Delete shopping list',
  delete_modal_content: 'Are you sure to delete this shopping list ? This action can not be undone.',
  delete_shopping_list_message: 'Shopping list deleted',
  duplicate_shopping_list_message: 'Shopping list duplicated',
  save_shopping_list_detail_message: 'Shopping list saved',
  submit_shopping_list_message: 'This Shopping list has been submitted for approval. Please contact to your super advisor to review your list',
  approve_shopping_list_message: 'This Shopping list is approved. You can continue to process and create order from this list',
  reject_shopping_list_message: 'This Shopping list is rejected by your supervisor',
  editor_title: 'Edit shopping list name and note',
  editor_name_label: 'Shopping list name',
  editor_note_label: 'Shopping list note',
  editor_name_empty_error: 'This field can\'t be blank',
  submit_for_approval: 'Submit for approval',
  exceed_inventory: 'The selected quantity exceeds available stock.',
  approve_confirm_message: 'Are you sure to approve this shopping list? Your reason for approval:',
  approve_confirm_title: 'Confirm approval',
  reject_confirm_message: 'Are you sure to reject this shopping list? Please let us know the reason so we can serve you better in the future.',
  reject_confirm_title: 'Confirm rejection',
  reason_label_accept: 'Reason for approval',
  reason_label_reject: 'Reason for rejection',
  reason: 'Reason',
};

const QUOTATION_CONTENTS = {
  ...COMMON_CONTENTS,
  page_title: 'Quotation',
  quote: 'Quote',
  quoted_price: 'Quoted price',
  contact_info: 'Contact information',
  shipping_address: 'Shipping address',
  billing_address: 'Billing address',
  created_at: 'Created at {{time}}',
  status_1: 'Under review',
  status_2: 'Under review',
  status_3: 'Price provided',
  status_4: 'Accepted',
  status_5: 'Rejected',
  status_7: 'Deal closed',
  status_all: 'All',
  status_6: 'Expired',
  status_under_review: 'Under review',
  status_pricing_provided: 'Price provided',
  status_accepted: 'Accepted',
  status_rejected: 'Rejected',
  status_deal_closed: 'Deal closed',
  status_expired: 'Expired',
  delete_quotation_message: 'Quotation deleted',
  duplicate_quotation_message: 'Quotation duplicated',
  empty_quotation_table_placeholder_header: 'No quotation yet',
  accept_quotation_modal_title: 'Are you sure to accept this quotation?',
  accept_quotation_modal_content: 'By accepting this quotation, you will close this negotiation and can continue to create an order from this quotation.',
  reject_quotation_modal_title: 'Are you sure to reject this quote?',
  reject_quotation_modal_content: 'By rejecting this quote, you will close this negotiation. Please let us know the reason so we can serve you better in the future.',
  re_quote_quotation_modal_title: 'Re-quote',
  re_quote_quotation_modal_content: 'Are you sure to re-quote this quotation?',
  accept_quote: 'Accept quote',
  reject_quote: 'Reject quote',
  quote_id: 'Quote ID',
  number_of_items: 'Number of items',
  status: 'Status',
  created_at_label: 'Created at',
  action: 'Action',
  location_choose: 'Choose your location',
  location_search_placeholder: 'Search location',
  location_select: 'Select location',
  no_customer_assigned: 'No customer assigned',
  expiration_date: 'Expiration date',
  quote_will_expire_in_days: 'This quote will expire in {{days}} days.',
  quote_expired: 'This quote is expired. Please submit a new quote request or contact us to receive an updated offer.',
  quote_will_expire_today: 'This quote will expire today',
  re_quote: 'Re-quote',
  shipping: 'Shipping',
  discount: 'Discount',
  tax: 'Estimated tax',
  download_pdf: 'Download PDF',
  export_pdf: 'Export to PDF',
  modal_export_pdf_title: 'Export quotation to PDF',
  modal_export_pdf_select_locale: 'Select language to export',
  accept_quote_message: 'Quote accepted',
  reject_quote_message: 'Quote rejected',
  update_quotation_message: 'Quotation updated',
  hide_history: 'Hide history',
  show_history: 'Show history',
};

const FINANCE_CREDIT_CONTENTS = {
  ...COMMON_CONTENTS,
  page_title: 'Finance & credit',
  account_overview: 'Account overview',
  total_orders: 'Total orders',
  total_payments: 'Total payments',
  total_purchases: 'Total purchases',
  credit_overview: 'Credit overview',
  date: 'Date',
  operation: 'Operation',
  credit_change: 'Credit change',
  outstanding_balance: 'Outstanding balance',
  credit_limit: 'Credit limit',
  used_credit: 'Used credit',
  available_credit: 'Available credit',
  status_reimbursed: 'Reimbursed',
  status_purchased: 'Purchased',
  status_reverted: 'Reverted',
  hide_credit_limit: 'Hide credit history',
  show_credit_limit: 'Show credit history',
  download_statement: 'Load statements',
  download: 'Download statements',
  empty_transaction_table_placeholder_header: 'No transaction yet',
  order_created: 'Order created',
  order_edited: 'Order edited',
  order_canceled: 'Order canceled',
  refund_created: 'Refund created',
  order_paid: 'Order paid',
  no_data_finance_ledger: 'No financial ledger data available.',
  all: 'All',
  debit: 'Debit',
  credit: 'Credit',
  not_available: 'N/A',
  data: 'Date',
  order_id: 'Order ID',
  transaction: 'Transaction',
  type: 'Type',
  value: 'Value',
  due_amount: 'Due amount',
  payment_overview: 'Payment overview',
  total_outstanding: 'Total outstanding',
  orders: 'order(s)',
  overdue_amount: 'Overdue amount',
  oldest_overdue_date: 'Oldest overdue date',
  days_late: 'days late',
  next_due_amount: 'Next due amount',
  next_due_date: 'Next due date',
  days_left: 'days left',
  failed_to_load_payment_overview: 'Failed to load payment overview',
  no_payment_data_available: 'No payment data available',
  view_all_payment_details: 'View all payment details',
  select_finance_type_label: 'View for',
  all_members: 'All members',
  finance_ledger: 'Financial ledger',
  // order history
  title: 'Payment History',
  order_date: 'Order date',
  due_date: 'Due date',
  payment_status: 'Payment status',
  order_value: 'Order value',
  quick_actions: 'Quick actions',
  paid: 'Paid',
  pending: 'Pending',
  authorized: 'Authorized',
  partially_paid: 'Partially paid',
  partially_refunded: 'Partially refunded',
  refunded: 'Refunded',
  voided: 'Voided',
  expired: 'Expired',
  send_payment: 'Send payment',
  send_payment_title: 'Send payment link to',
  send_payment_text_field_label: 'Use another email (if needed)',
  send: 'Send',
  search_by_order_id: 'Search by Order ID',
  filter_by: 'Filter by',
  no_order_history: 'No order history available',
  invalid_email_error: 'This email is invalid',
};

const CUSTOMER_PERMISSION_CONTENTS = {
  ...COMMON_CONTENTS,
  name: 'Name',
  type: 'Type',
  phone: 'Phone',
  email: 'Email',
  role: 'Role',
  status: 'Status',
  last_update: 'Last update',
  action: 'Action',
  member_role: 'Member roles',
  page_subtitle: 'Manage roles and permissions within your company location',
  role_create: 'Create Role',
  location_choose: 'Choose your location',
  location_search_placeholder: 'Search location',
  location_select: 'Select location',
  location_change_warning: 'If you change your location, the current catalog may not be available. The CSV file you uploaded will be deleted.',
  create_role: 'Create role',
  invite_member: 'Invite member',
  invite_member_modal_title: 'Invite new member',
  invite_member_modal_first_name: 'First name',
  invite_member_modal_last_name: 'Last name',
  edit_member_modal_title: 'Edit team member',
  invite_member_modal_no_role_name: 'Role name is required',
  save: 'Save',
  page_members_title: 'Company members',
  page_members_subtitle: 'Manage all members within company location',
  create_role_modal_title: 'Create new role',
  role_name: 'Role name',
  next: 'Next',
  select_base_role: 'Select base role',
  no_permission_view_roles: 'You don\'t have permissions to view roles',
  no_permission_view_members: 'You don\'t have permissions to view members',
  can_not_view_members: 'You don\'t have permission to view members',
  can_not_view_roles: 'You don\'t have permission to view roles',
  // Permissions labels
  role_manage_button: 'Role manage',
  view_all_orders: 'View the list of orders that all customers have placed',
  view_own_orders: 'View their own orders for the company location',
  edit_shipping_billing_address: 'Edit billing and shipping addresses from their account',
  read_shopping_list: 'View Shopping lists from all members in company location',
  write_shopping_list: 'Create/Edit/Delete',
  submit_shopping_list: 'Submit shopping list',
  approve_shopping_list: 'Approve draft status list',
  create_order_shopping_list: 'Create order from approved shopping list',
  write_quotations: 'Request for quote',
  read_quotations: 'View quotes from all members in company location',
  create_order_from_quotation: 'Create order from quote',
  create_shopping_list_from_csv: 'Create shopping list from CSV upload',
  create_order_from_csv: 'Create order from CSV upload',
  create_shopping_list_from_sku: 'Create shopping list from SKU',
  create_order_from_sku: 'Create order from SKU',
  purchase_online_store: 'Complete purchases from online store',
  purchase_online_store_help_text: 'Includes adding products to the cart, proceeding to checkout and paying for the order.',
  read_roles: 'View',
  write_roles: 'Create/Edit/Delete',
  read_members: 'View',
  write_members: 'Create/Edit/Delete',
  order_history: 'Order history',
  shipping_and_billing: 'Shipping and billing',
  shopping_list: 'Shopping list',
  csv_upload: 'CSV upload',
  members: 'User management',
  roles: 'Role management',
  sku: 'Quick order SKU',
  quotes: 'Quotes',
  purchase: 'Purchase from online store',
  active: 'Active',
  permissions: 'permissions',
  delete_member_modal_title: 'Are you sure?',
  delete_member_modal_content: 'Are you sure you want to delete',
  finance_credit: 'Finance and payment',
  enable_finance_account: 'View Account overview',
  enable_finance_payment: 'View Payment overview',
  enable_finance_credit_limit: 'View Credit limit overview',
  enable_finance_order_history: 'View Order history overview',
  enable_finance_ledger: 'View Financial ledger',
};

const BLOCK_CHECKOUT_CONTENTS = {
  blocking_pending_customer_permission: 'Pending customer permission',
  blocking_checkout_message: 'Sorry, you are not allowed to proceed to checkout.',
  exceed_credit_limit_title: 'Exceed credit limit',
  banner_exceed_credit_limit_title: 'Order value has exceed your company available credit.',
  banner_exceed_credit_limit_description: 'Please reduce your order size or pay your outstanding balance to avoid any disruptions in the future',
  available_credit: 'Available credit limit:',
};

export const CUSTOMER_ACCOUNT_CONTENTS = {
  [ExtensionType.CsvUpload]: CSV_UPLOAD_CONTENTS,
  [ExtensionType.QuickOrder]: QUICK_ORDER_CONTENTS,
  [ExtensionType.ShoppingList]: SHOPPING_LIST_CONTENTS,
  [ExtensionType.CustomerPermission]: CUSTOMER_PERMISSION_CONTENTS,
  [ExtensionType.Quotation]: QUOTATION_CONTENTS,
  [ExtensionType.FinanceCredit]: FINANCE_CREDIT_CONTENTS,
  [ExtensionType.BlockCheckout]: BLOCK_CHECKOUT_CONTENTS,
};
