export const defaultRoles = [
  {
    id: null,
    name: 'admin',
    type: 'default',
    permissions: [
      "view_all_orders",
      "view_own_orders",
      "edit_shipping_billing_address",
      "read_members",
      "write_members",
      "read_shopping_list",
      "write_shopping_list",
      "approve_shopping_list",
      "create_order_shopping_list",
      "create_shopping_list_from_csv",
      "create_order_from_csv",
      "create_shopping_list_from_sku",
      "create_order_from_sku",
      "purchase_online_store",
      "read_roles",
      "write_roles",
      "read_quotations",
      "write_quotations",
      "create_order_from_quotation",
      "enable_finance_account",
      "enable_finance_payment",
      "enable_finance_credit_limit",
      "enable_finance_order_history",
      "enable_finance_ledger",
    ]
  },
  {
    id: null,
    name: 'senior_buyer',
    type: 'default',
    permissions: [
      "view_own_orders",
      "read_shopping_list",
      "write_shopping_list",
      "approve_shopping_list",
      "create_order_shopping_list",
      "create_shopping_list_from_csv",
      "create_order_from_csv",
      "create_shopping_list_from_sku",
      "create_order_from_sku",
      "purchase_online_store",
      "read_quotations",
      "write_quotations",
      "create_order_from_quotation",
      "enable_finance_account",
      "enable_finance_payment",
      "enable_finance_credit_limit",
      "enable_finance_order_history",
      "enable_finance_ledger",
    ]
  },
  {
    id: null,
    name: 'junior_buyer',
    type: 'default',
    permissions: [
      "view_own_orders",
      "write_shopping_list",
      "submit_shopping_list",
      "create_order_shopping_list",
      "create_shopping_list_from_csv",
      "create_shopping_list_from_sku",
      "write_quotations",
      "enable_finance_account",
      "enable_finance_payment",
      "enable_finance_credit_limit",
      "enable_finance_order_history",
      "enable_finance_ledger",
    ]
  }
];

export const DEFAULT_INITIAL_OPEN_DISCLOSURE_LIST = [
  'order-history',
  'shipping-and-billing',
  'purchases',
  'members',
  'shopping-list',
  'csv-upload',
  'sku',
  'roles',
  'quotes',
  'finance-credit',
];
